import { MOVIES, SINGLE_MOVIE, SERIES, SINGLE_SERIES } from './globals';

export const FETCH_MOVIES_BEGIN   = `${MOVIES}/FETCH_MOVIES_BEGIN`;
export const FETCH_MOVIES_SUCCESS = `${MOVIES}/FETCH_MOVIES_SUCCESS`;
export const FETCH_MOVIES_ERROR   = `${MOVIES}/FETCH_MOVIES_ERROR`;

// export const FETCH_SINGLE_MOVIE_BEGIN   = `${SINGLE_MOVIE}/FETCH_SINGLE_MOVIE_BEGIN`;
export const FETCH_SINGLE_MOVIE_SUCCESS = `${SINGLE_MOVIE}/FETCH_SINGLE_MOVIE_SUCCESS`;
// export const FETCH_SINGLE_MOVIE_ERROR   = `${SINGLE_MOVIE}/FETCH_SINGLE_MOVIE_ERROR`; 

export const FETCH_SERIES_BEGIN   = `${SERIES}/FETCH_SERIES_BEGIN`;
export const FETCH_SERIES_SUCCESS = `${SERIES}/FETCH_SERIES_SUCCESS`;
export const FETCH_SERIES_ERROR   = `${SERIES}/FETCH_SERIES_ERROR`;

// export const FETCH_SINGLE_SERIES_BEGIN   = `${SINGLE_SERIES}/FETCH_SINGLE_SERIES_BEGIN`;
export const FETCH_SINGLE_SERIES_SUCCESS = `${SINGLE_SERIES}/FETCH_SINGLE_SERIES_SUCCESS`;
// export const FETCH_SINGLE_SERIES_ERROR   = `${SINGLE_SERIES}/FETCH_SINGLE_SERIES_ERROR`; 

export const SORTING_DATA = `SORTING_DATA`;
export const CLEAR_SORTING_DATA = `CLEAR_SORTING_DATA`;
